In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

In [2]:
data=pd.read_csv("Preprocessed_data.csv")

In [3]:
data.head()

Source.IP  Source.Port  Destination.IP  Destination.Port  Protocol  \
0  3.232259e+09       3821.0     180881160.0            3128.0       6.0   
1  3.232259e+09       4836.0     180881160.0            3128.0       6.0   
2  3.232259e+09       3773.0     180881160.0            3128.0       6.0   
3  3.232259e+09       1523.0     180881159.0            3128.0       6.0   
4  3.232248e+09       3053.0     180881159.0            3128.0       6.0   

   Flow.Duration  Total.Fwd.Packets  Total.Backward.Packets  \
0          341.0                1.0                     1.0   
1          341.0                1.0                     1.0   
2          327.0                1.0                     1.0   
3          313.0                1.0                     1.0   
4          766.0                1.0                     2.0   

   Total.Length.of.Fwd.Packets  Total.Length.of.Bwd.Packets  ...  Active.Mean  \
0                          6.0                          6.0  ...          0.0   
1                          6.0                          6.0  ...          0.0   
2                          6.0                          6.0  ...          0.0   
3                          6.0                          6.0  ...          0.0   
4                          6.0                         12.0  ...          0.0   

   Active.Std  Active.Max  Active.Min  Idle.Mean  Idle.Std  Idle.Max  \
0         0.0         0.0         0.0        0.0       0.0       0.0   
1         0.0         0.0         0.0        0.0       0.0       0.0   
2         0.0         0.0         0.0        0.0       0.0       0.0   
3         0.0         0.0         0.0        0.0       0.0       0.0   
4         0.0         0.0         0.0        0.0       0.0       0.0   

   Idle.Min  L7Protocol  ProtocolName  
0       0.0       178.0        AMAZON  
1       0.0       178.0        AMAZON  
2       0.0       178.0        AMAZON  
3       0.0       178.0        AMAZON  
4       0.0       178.0        AMAZON  

[5 rows x 84 columns]

In [13]:
x=data.iloc[:,0:83]
y=data.iloc[:,-1]

In [14]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [15]:
x=pd.DataFrame(x,columns=data.columns[0:83])
x

Source.IP  Source.Port  Destination.IP  Destination.Port  Protocol  \
0        0.945448    -1.738083       -0.659034         -0.166763 -0.143452   
1        0.945448    -1.689242       -0.659034         -0.166763 -0.143452   
2        0.945448    -1.740392       -0.659034         -0.166763 -0.143452   
3        0.945448    -1.848659       -0.659034         -0.166763 -0.143452   
4        0.945441    -1.775038       -0.659034         -0.166763 -0.143452   
...           ...          ...             ...               ...       ...   
420497   0.945435     0.844724       -0.659034         -0.166763 -0.143452   
420498   0.945470     0.739778       -0.659034         -0.166763 -0.143452   
420499   0.945435     0.555773       -0.659034         -0.166763 -0.143452   
420500   0.945440     0.555965       -0.659034         -0.166763 -0.143452   
420501   0.945463     0.646236       -0.659034         -0.166763 -0.143452   

        Flow.Duration  Total.Fwd.Packets  Total.Backward.Packets  \
0           -0.519110          -0.098693               -0.098722   
1           -0.519110          -0.098693               -0.098722   
2           -0.519111          -0.098693               -0.098722   
3           -0.519111          -0.098693               -0.098722   
4           -0.519098          -0.098693               -0.097690   
...               ...                ...                     ...   
420497      -0.519112          -0.098693               -0.098722   
420498      -0.519109          -0.098693               -0.096657   
420499      -0.518757          -0.098693               -0.098722   
420500      -0.519117          -0.098693               -0.098722   
420501      -0.519112          -0.098693               -0.097690   

        Total.Length.of.Fwd.Packets  Total.Length.of.Bwd.Packets  ...  \
0                          -0.05275                    -0.034630  ...   
1                          -0.05275                    -0.034630  ...   
2                          -0.05275                    -0.034630  ...   
3                          -0.05275                    -0.034630  ...   
4                          -0.05275                    -0.034626  ...   
...                             ...                          ...  ...   
420497                     -0.05275                    -0.034630  ...   
420498                     -0.05275                    -0.034621  ...   
420499                     -0.05275                    -0.034630  ...   
420500                     -0.05275                    -0.034634  ...   
420501                     -0.05275                    -0.034626  ...   

        min_seg_size_forward  Active.Mean  Active.Std  Active.Max  Active.Min  \
0                  -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
1                  -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
2                  -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
3                  -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
4                  -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
...                      ...          ...         ...         ...         ...   
420497             -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
420498             -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
420499             -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
420500             -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   
420501             -0.788081    -0.121102   -0.097095   -0.135927   -0.100295   

        Idle.Mean  Idle.Std  Idle.Max  Idle.Min  L7Protocol  
0       -0.371883 -0.178077 -0.380515 -0.355132    0.800458  
1       -0.371883 -0.178077 -0.380515 -0.355132    0.800458  
2       -0.371883 -0.178077 -0.380515 -0.355132    0.800458  
3       -0.371883 -0.178077 -0.380515 -0.355132    0.800458  
4       -0.371883 -0.178077 -0.380515 -0.355132    0.800458  
...           ...       ...     

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.3, random_state = 42)

# KNN

In [7]:
knn_clf=KNeighborsClassifier()

In [8]:
params = { 'n_neighbors': [3,7,11,21],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan'] }
gs_knn = GridSearchCV(knn_clf, params, cv = 10, n_jobs = -1)

In [ ]:
%%time
gs_knn=gs_knn.fit(X_train,y_train)

In [ ]:
gs_knn.best_params_

In [17]:
knn=KNeighborsClassifier(n_neighbors = 3, metric='manhattan', weights='distance')

In [19]:
%%time
knn.fit(X_train,y_train)

Wall time: 2min 14s


KNeighborsClassifier(metric='manhattan', n_neighbors=3, weights='distance')

In [20]:
%%time
knn.score(X_test, y_test)

Wall time: 23min 23s


0.9423389430127387

In [21]:
%%time
y_pred = knn.predict(X_test)

Wall time: 21min


In [22]:
print(classification_report(y_test, y_pred))

C:\Users\chara\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                   precision    recall  f1-score   support

           AMAZON       0.91      0.80      0.85      2958
            APPLE       0.92      0.88      0.90      2977
     APPLE_ICLOUD       0.92      0.97      0.95      2950
     APPLE_ITUNES       0.93      0.95      0.94      3062
    CITRIX_ONLINE       0.83      0.91      0.87        11
       CLOUDFLARE       0.98      0.97      0.97      3046
    CONTENT_FLASH       0.99      1.00      1.00      2950
           DEEZER       1.00      0.28      0.43        18
              DNS       1.00      0.99      1.00      2990
          DROPBOX       0.92      0.89      0.91      3028
         EASYTAXI       0.96      0.98      0.97      3083
             EBAY       0.94      0.96      0.95      3025
          EDONKEY       0.85      0.41      0.55        27
         FACEBOOK       0.94      0.94      0.94      2932
      FTP_CONTROL       1.00      1.00      1.00         9
         FTP_DATA       0.97      0.99      0.98      3

In [23]:
print(confusion_matrix(y_test, y_pred))

[[2361   19    5 ...   22    4    0]
 [  10 2633  107 ...    0    1    0]
 [   1   25 2872 ...    6    0    1]
 ...
 [   3    3    0 ... 3035    2    0]
 [   6    3    0 ...    3 2592    1]
 [   0    2    0 ...    0    0 2838]]


In [24]:
count1=0
for i in range(len(y_pred)):

    if y_pred[i]==y_test.values[i]:
        count1=count1+1
print("Testing accuracy:",(count1/(len(y_test.values))*100))

Testing accuracy: 94.23389430127386


In [30]:
y_pred_train=knn.predict(X_train)

In [31]:
print(confusion_matrix(y_train,y_pred_train))

[[7042    0    0 ...    0    0    0]
 [   0 7023    0 ...    0    0    0]
 [   0    0 7050 ...    0    0    0]
 ...
 [   0    0    0 ... 6920    0    0]
 [   0    0    0 ...    0 7069    0]
 [   0    0    0 ...    0    0 6952]]


In [33]:
count=0
for i in range(len(y_pred_train)):
    if y_pred_train[i]==y_train.values[i]:
        count=count+1
print("Training accuracy :",(count/len(y_train))*100)

Training accuracy : 100.0


# Decision Tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
gs_dt = DecisionTreeClassifier(random_state=42)
params = { 'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [10,11,12,13,14,15,16,17] }
gs_dt = GridSearchCV(gs_dt, params, cv = 10, n_jobs = -1)

In [ ]:
gs_dt=gs_dt.fit(X_train,y_train)

In [ ]:
gs_dt.best_params_

In [27]:
dt=DecisionTreeClassifier(criterion='entropy',max_depth=10,splitter='best',random_state=42)

In [28]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=42)

In [29]:
dt.score(X_test,y_test)

0.9999841459837814

In [34]:
%%time
y_pred_dt = dt.predict(X_test)

Wall time: 139 ms


# Random Forest

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
gs_rf = RandomForestClassifier()
param_grid = {'max_depth':[30,40,50],
              'n_estimators':[20,30,40,50],  
              'max_features':['auto','log2'],
              'criterion':['gini','entropy']}

In [ ]:
gs_rf = GridSearchCV(estimator = gs_rf, param_grid = param_grid, scoring='accuracy', cv=6)

In [37]:
rf=RandomForestClassifier(max_depth=40, n_estimators=50, criterion='entropy')

In [38]:
%%time
rf.fit(X_train, y_train)

Wall time: 4min 5s


RandomForestClassifier(criterion='entropy', max_depth=40, n_estimators=50)

In [39]:
%%time
rf.score(X_test, y_test)

Wall time: 4.11 s


0.9837971954245309

In [40]:
%%time
y_pred_rf = rf.predict(X_test)

Wall time: 3.92 s


In [41]:
print(classification_report(y_test, y_pred_rf))

C:\Users\chara\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                   precision    recall  f1-score   support

           AMAZON       0.96      0.97      0.96      2958
            APPLE       0.99      0.99      0.99      2977
     APPLE_ICLOUD       1.00      1.00      1.00      2950
     APPLE_ITUNES       0.99      1.00      1.00      3062
    CITRIX_ONLINE       1.00      1.00      1.00        11
       CLOUDFLARE       1.00      1.00      1.00      3046
    CONTENT_FLASH       1.00      1.00      1.00      2950
           DEEZER       1.00      0.44      0.62        18
              DNS       1.00      1.00      1.00      2990
          DROPBOX       0.98      0.95      0.97      3028
         EASYTAXI       0.99      1.00      1.00      3083
             EBAY       0.99      0.99      0.99      3025
          EDONKEY       1.00      0.63      0.77        27
         FACEBOOK       0.96      0.97      0.97      2932
      FTP_CONTROL       1.00      1.00      1.00         9
         FTP_DATA       0.99      1.00      1.00      3

In [42]:
print(confusion_matrix(y_test, y_pred_rf))

[[2855    2    0 ...    5    0    0]
 [   0 2935    1 ...    3    0    0]
 [   0    3 2940 ...    0    0    0]
 ...
 [   5    1    0 ... 3064    1    0]
 [   0    1    0 ...    0 2792    6]
 [   0    0    0 ...    0    0 3028]]
